name: votoerddap
channels:
  - conda-forge
dependencies:
    - argopy
    - jupyterlab
    - matplotlib
    - xarray
    - cartopy
    - glidertools
    - cmocean
    - jupyterlab_widgets
    - ipywidgets
    - ioos_qc
